version: '3.4'

services:
  postgres-db:
    image: postgres:15
    env_file:
      - .env
    ports:
      - "5432:5432"
    container_name: postgres-container-auth
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis-auth
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    restart: always

volumes:
  postgres-data:
  redis_data: