version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-auth
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -p ${POSTGRES_PORT}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  redis:
    image: redis:7.2.4
    container_name: redis-auth
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    restart: always

  api:
    build: .
    container_name: api-auth
    ports:
      - ${AUTH_API_PORT}:${AUTH_API_PORT}
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy

  nginx:
    image: nginx:1.19.2
    container_name: nginx-auth
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs/confd:/etc/nginx/conf.d:ro
    depends_on:
      - api
    ports:
      - "80:80"

volumes:
  postgres-data:
  redis_data:
